name: CI

on: [push, pull_request]

jobs:
  build-windows:

    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Restore vcpkg cache
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: 91dd61bd441a68b4017b61011d0350b2e6aeeccf
    - name: Prepare environment
      run: |
        mkdir x64\Release
        & $Env:VCPKG_ROOT\vcpkg integrate install
        ((Get-Content -path "$Env:VCPKG_ROOT\ports\poco\portfile.cmake") -replace "VCPKG_TARGET_IS_WINDOWS", "false") -replace "lib/cmake/Poco", "cmake" | Set-Content -Path "$Env:VCPKG_ROOT\ports\poco\portfile.cmake"
    - name: Build sanjuuni
      run: |
        function Invoke-Environment {
            param
            (
                # Any cmd shell command, normally a configuration batch file.
                [Parameter(Mandatory=$true)]
                [string] $Command
            )

            $Command = "`"" + $Command + "`""
            cmd /c "$Command > nul 2>&1 && set" | . { process {
                if ($_ -match '^([^=]+)=(.*)') {
                    [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
                }
            }}

        }

        Invoke-Environment "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        Set-Item ENV:ExternalCompilerOptions /DHAS_OPENCL
        bash -c @'
        printf '// Generated automatically; do not edit!\n#include <string>\nnamespace OpenCL {std::string get_opencl_c_code() { return "' > src/cc-pixel-cl.cpp
	      sed -n -e '/#ifndef OPENCV/{:a; N; /#endif/!ba; d}; s/$/\\n\\/g; s/"/\\"/g; p' src/cc-pixel.cpp >> src/cc-pixel-cl.cpp
	      echo '";}}' >> src/cc-pixel-cl.cpp
        '@
        msbuild "sanjuuni.sln" /p:Configuration=Release
        # Remove buildtrees that kill the cache
        Remove-Item vcpkg\buildtrees\* -Force -Recurse -ErrorAction SilentlyContinue
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: sanjuuni-Artifact
        path: |
          x64\Release\sanjuuni.exe
